Repository skaiworldwide-oss/agensgraph, pull requests merged in 2025-04, with the labels that each got.

#713 Implement tab completion for Graph CREATE,DROP and psql meta command
  src/bin/psql/tab-complete.c
Labels: enhancement

#722 Add quickstart guide with docker in README
  README.md
Labels: enhancement

#723 [v2.15] chore: Add quickstart with docker section in README
  README.md
Labels: v2.15

#610 fix: Columns not visible when using a VLE. (#609)
  src/backend/parser/parse_graph.c
  src/test/regress/expected/cypher_dml.out
  src/test/regress/expected/cypher_dml2.out
  src/test/regress/expected/cypher_privileges.out
  src/test/regress/sql/cypher_dml2.sql
  src/test/regress/sql/cypher_privileges.sql
Labels: bug
